from __future__ import annotations

import argparse
import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _slugify(value: str) -> str:
    token = re.sub(r"[^a-zA-Z0-9._-]+", "-", str(value or "").strip().lower())
    token = re.sub(r"-+", "-", token).strip("-.")
    return token or "job"


def _utc_now() -> str:
    return datetime.now(UTC).isoformat()


def _read_text(path: str | None, inline: str | None) -> str:
    if path:
        return Path(path).read_text(encoding="utf-8").strip()
    return str(inline or "").strip()


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Initialize a versioned E2E job workspace.")
    parser.add_argument("--job-id", default="", help="Optional job id. If not provided it is generated from title.")
    parser.add_argument("--title", required=True, help="Short job title.")
    parser.add_argument("--server-name", required=True, help="Runtime server selector, for example kadwa.zeta")
    parser.add_argument("--target-id", default="netcorner-nuxt-pl", help="Target id from framework targeting registry")
    parser.add_argument("--scenario", default="", help="Scenario prompt text")
    parser.add_argument("--scenario-file", default="", help="Read scenario prompt from file")
    parser.add_argument(
        "--seed-path",
        action="append",
        default=[],
        help="Optional seed path(s) for exploratory analysis, repeatable",
    )
    parser.add_argument(
        "--seed-paths-csv",
        default="",
        help="Optional comma-separated seed paths for exploratory analysis",
    )
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing job files.")
    args = parser.parse_args()

    scenario_text = _read_text(args.scenario_file or None, args.scenario or None)
    if not scenario_text:
        raise SystemExit("Scenario content is required via --scenario or --scenario-file")

    repo_root = _repo_root()
    jobs_root = repo_root / "work" / "e2e-jobs"
    job_id = _slugify(args.job_id) if str(args.job_id or "").strip() else _slugify(args.title)
    job_dir = jobs_root / job_id
    if job_dir.exists() and not args.overwrite:
        raise SystemExit(f"Job already exists: {job_dir}. Use --overwrite to rewrite scaffold files.")

    (job_dir / "analysis" / "cache").mkdir(parents=True, exist_ok=True)
    (job_dir / "handoff").mkdir(parents=True, exist_ok=True)
    (job_dir / "implementation").mkdir(parents=True, exist_ok=True)

    csv_seed_paths = [item.strip() for item in str(args.seed_paths_csv or "").split(",") if item.strip()]
    merged_seed_paths: list[str] = []
    for item in [*args.seed_path, *csv_seed_paths]:
        token = str(item).strip()
        if token and token not in merged_seed_paths:
            merged_seed_paths.append(token)

    job_payload: dict[str, Any] = {
        "job_id": job_id,
        "title": str(args.title).strip(),
        "status": "draft",
        "target": {
            "target_id": str(args.target_id).strip(),
            "server_name": str(args.server_name).strip(),
        },
        "seed_paths": merged_seed_paths,
        "created_at_utc": _utc_now(),
        "updated_at_utc": _utc_now(),
    }

    _write_json(job_dir / "job.json", job_payload)

    (job_dir / "scenario.md").write_text(
        "\n".join(
            [
                f"# E2E Job {job_id}",
                "",
                "## Title",
                str(args.title).strip(),
                "",
                "## Scenario Prompt",
                scenario_text,
                "",
                "## Notes",
                "- Add any extra business constraints here.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    (job_dir / "analysis" / "open_questions.md").write_text(
        "# Open Questions\n\n- [ ] Fill after exploratory analysis.\n",
        encoding="utf-8",
    )
    (job_dir / "analysis" / "answers.md").write_text(
        "# User Answers\n\n- Add answers to open questions here.\n",
        encoding="utf-8",
    )
    (job_dir / "analysis" / "journey_map.md").write_text(
        "# Journey Map\n\n- To be generated by analysis pass.\n",
        encoding="utf-8",
    )
    (job_dir / "analysis" / "locator_gaps.md").write_text(
        "# Locator Gaps\n\n- To be generated by analysis pass.\n",
        encoding="utf-8",
    )
    (job_dir / "analysis" / "refined_behavior_contract.md").write_text(
        "# Refined Behavior Contract\n\nStatus: DRAFT\n\n- To be generated by analysis pass.\n",
        encoding="utf-8",
    )
    _write_json(
        job_dir / "handoff" / "analysis_contract.json",
        {
            "job_id": job_id,
            "status": "draft",
            "ready_for_implementation": False,
            "analysis_outputs": {},
            "updated_at_utc": _utc_now(),
        },
    )
    (job_dir / "implementation" / "implementation_notes.md").write_text(
        "# Implementation Notes\n\n- To be filled by implementation pass.\n",
        encoding="utf-8",
    )

    print(f"Initialized E2E job workspace: {job_dir}")
    print(f"Edit scenario: {job_dir / 'scenario.md'}")
    print(f"Next step: run analysis pass for this job id: {job_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
