class ProductOpinionPageLocators:
    CONTAINER_reviews = "//div[@id='Opinie']"
    CONTAINER_add_review = "//div[@data-name='addReview']"
    INPUT_add_review = CONTAINER_add_review + "//textarea"
    BUTTON_add_review = CONTAINER_add_review + "//button"
    CONTAINER_reviews_list = "//div[@data-name='reviewsList']"
    ELEMENTS_customer_review = "//div[@data-name='review']//div[@class='wrap-text']"
    BUTTON_extend_hidden_customer_reviews = "//button/u[contains(text(), 'Pokaż kolejne')]"


class ProductPagePriceContainerLocators:
    CONTAINER_product_price = "//div[@data-name='addToCartDesktop']/div[@data-name='addToCartWrapper']"
    ELEMENT_min_qty = CONTAINER_product_price + "//span[@data-min-qty]"
    ELEMENT_base_price = CONTAINER_product_price + "//*[@data-price-type='base']"
    ELEMENT_final_price = CONTAINER_product_price + "//*[@data-price-type='final']"
    ELEMENT_price_badge = CONTAINER_product_price + "//div[@data-name='badge']//div[@class='text-base']"
    ELEMENT_omnibus_price = CONTAINER_product_price + "//*[@data-price-type='omnibus']"
    ELEMENT_outlet_price = CONTAINER_product_price + "//*[@data-price-type='outlet']"
    ELEMENT_promo_code_price = CONTAINER_product_price + "//*[@data-price-type='coupon']"
    BUTTON_add_to_cart = CONTAINER_product_price + "//button[@data-name='addToCartButton']"
    ELEMENT_product_availability_status = CONTAINER_product_price + \
                                          "//div[contains(@data-name, 'statusAvailable')]//div[contains(@class, 'leading')]"
    ELEMENT_product_availability_status_subtitle = CONTAINER_product_price + \
                                                   "//div[contains(@data-name, 'statusAvailable')]//div[contains(@class, 'text-gray-grave')]"
    ELEMENT_product_lift_service_available = CONTAINER_product_price + "//div[contains(text(),'z wniesieniem')]"
    ELEMENT_product_temporarily_unavailable = CONTAINER_product_price + "//div[contains(text(),'tymczasowo niedostępny')]"
    ELEMENT_product_unavailable = "//div[contains(text(),'trwale niedostępny')]"
    ELEMENT_product_limited_sale_available = CONTAINER_product_price + "//div[contains(text(),'jest limitowana')]"
    ELEMENT_product_limited_sale_status = ELEMENT_product_limited_sale_available + "/following-sibling::div//span[contains(text(), Pozostało)]"
    ELEMENT_sign_to_newsletter = CONTAINER_product_price + "(//span[contains(., 'Powiadom o')])[2]"
    ELEMENT_promo_code_label = CONTAINER_product_price + "//div[contains(text(), 'Skopiuj kod i wklej w koszyku:')]"
    ELEMENT_promo_code_value = ELEMENT_promo_code_label + "/following-sibling::div[@data-name='copyToClipboard']/div"
    ELEMENT_storehouses_availability_note = CONTAINER_product_price + "//div[contains(text(), 'Dostępny w salonach')]"
    ELEMENT_storehouses_availability_details = CONTAINER_product_price + "//span[contains(text(), 'Sprawdź dostępność')]"
    ELEMENT_alert = "//h2[contains(text(), 'Produkt nie został dodany do koszyka')]"
    ELMENT_limited_sale_alert = "//*[contains(normalize-space(text()),'Przekroczono limit liczby sztuk produktu')and contains(normalize-space(text()),'w sprzedaży limitowanej.')]"


class ProductPageLocators(ProductPagePriceContainerLocators):
    ELEMENT_product_page_code = "//h1[@data-name='productName']"
    ELEMENT_product_name = "//h1[@data-name='productName']"
    ELEMENT_product_maker = "//div[@data-name='specsGroup']//a[contains(@href, 'producer')]/span"
    ELEMENT_product_erp_code = "//p[contains(text(), 'Kod systemowy')]"
    ELEMENT_sign_to_newsletter = "(//span[contains(., 'Powiadom o')])[2]"
    ELEMENT_product_label_within_main_box = "//div[@data-name='productLabels']//img[contains(@alt, '{}')]"
    ELEMENT_product_label_within_product_description = "//div[@data-name='productAdditionalInfo']//img[contains(@alt, '{}')]"
    ELEMENT_product_breadcrumbs = "//div[@data-role='breadcrumbs']//a"
    ELEMENT_product_label_within_product_description_url = "//div[@data-name='productAdditionalInfo']//a[contains(@href, '{}')]"
    ELEMENT_promotion = "//div[@id='promocje']//p[contains(text(), '{promotion_title}')]"
    BUTTON_add_to_wishlist = "//button[@data-name='productAction']//span[contains(text(), 'Lista')]"
    META_info_product_id = "//meta[@property='product:retailer_part_no']"
